### ISSUE TITLE
Interactive checklist

### ISSUE THREAD

**Issue by parnic** [parnic/tesla-model-y-checklist#1]
# Tesla Model Y Delivery Checklist

The following is a distillation of posts from [`r/TeslaModelY`](https://www.reddit.com/r/TeslaModelY/). The list
is not meant to replace Tesla's QC and thus doesn't offer 100% coverage. Rather, these contributions from MY owners
who already walked the path aim to cover recurring problems that unfortunately seem to escape quality control (QC) at
the factory as well as at the service centers.

Use it to guide your inspection, document findings, assemble a list of problems to be handled by Tesla as pre-delivery issue(s)
or refuse delivery.

Only a fraciton of the potential issues can be inspected without unlocking the vehicle. Unless the service center staff offers to
unlock, you cannot do so prior to accepting delivery on your phone. To facilitate making that decision the list begins with
items that could be inspected while the car is locked.

### Locked

- [ ] Check the head light fit
- [ ] Inspect the paint around intake vents on the front bumper
- [ ] Inspect the frunk, look for paint defects, dents and signs of improper closing by the sides of the T logo
- [ ] Make sure the hood sits flush with the quarter panels and frunk
- [ ] Inspect that the windshield isn't installed shifted (the gaps between the glass and A pillar on either side
should be approximately equal). An improperly installed windshield causes significant wind noise at highway speeds.
- [ ] Check for uneven/wide panel gaps and that panels are flush to car
- [ ] Check for trim stains
- [ ] Check all 4 door levers
- [ ] Check all wheels, make sure they aren’t scratched
- [ ] Confirm all 4 hubcaps are present and properly attached
- [ ] Check for dings on pillars
- [ ] Inspect the paint on the outside and the door jams, ensure panel corners do not have chips
- [ ] Check for damage to black rocker panels
- [ ] Check the tail light fit
> * __Photo:__ [tail light (passenger side) not flush with panel](https://imgur.com/aPzCKKG)
> * __Fix:__ not yet available
- [ ] Check charging port fit (driver side)
- [ ] Inspect the tail lights for condensation
- [ ] Inspect the undercarriage, look for damage, missing screws, or screws that are sticking out
- [ ] Inspect all wheel wells. Each wheel well is fitted with noise dampener covers that are attached to the body with a combination of plastic
pins (pushed in all the way) and metal threaded pins (sticking out) with plastric nuts. Confirm that all plastic pins are present
(there are no empty holes) and all metal pins (2 in each front wheel well, 4 in each rear wheel well) are present and properly attached.
> * __Photo:__ [threaded pins with and without plastic nuts](https://imgur.com/6KqcVg4)
> * __Fix:__ mobile service can fix it in minutes

### Unlocked

- [ ] Turn on the lights on the car including: fog lights, head lights, tail lights, reverse light, brake, signal lights (head light signal and side signal lights)
- [ ] Check that wipers function correctly and look for potential wiper dings on hood
- [ ] Inspect every glass and make sure there are no scratches or cracks 
- [ ] Check for trim scratches on windows due to a software bug that doesn't automatically lower the window when opening the door
- [ ] Verify that the charge port opens and closes
- [ ] Verify that the rubber gasket is properly attached to the bottom of all 4 doors.
> * __Photo:__ [rubber gasket loose on driver door bottom](https://imgur.com/AodUDfg)
> * __Fix:__ service center, replace rubber gaskets

## Interior

- [ ] Inspect the screen for scratches
- [ ] Inspect the center console scratches, dings, etc.
- [ ] Inspect the dash for scratches
- [ ] Verify that wireless charging works on both sides
- [ ] Confirm wired charging works (1 x USB-A in front, 3 x USB-C, front and back)
- [ ] Open and close the glovebox
- [ ] Open and close windows using one click open close and manually open and close (make sure there are no noises and they stay up when you close, and when they
go down they do all the way down for front two windows. The rear two windows don't go down all the way.
- [ ] Verify backup camera
- [ ] Play a familiar track through the sound system and confirm that all speakers work (use the balance and fader controls) and there
are no unexpected clicks, etc.
- [ ] Fold mirrors
- [ ] Check all interior lights, and that all reading lights turn on with a press
- [ ] Check windshield all around
- [ ] Inspect the headliner all around (no grease, damage or scuffs)
- [ ] Inspect both coat hooks (should extend, retract and latch)
- [ ] Inspect the steering wheel, check front & back for scratches or tears
- [ ] Check that turn signal and drive selection stalks work and actuate smoothly
- [ ] Look for scratches on the passenger side door sill
- [ ] Check seats for scuffs/damage/bad seams
- [ ] Verify all front seat adjustments, including lumbar support
- [ ] Confirm seat warmers work 
- [ ] Confirm the middle seat on back row is flush at both ends
- [ ] Confirm that back seats recline adjustment works correctly
- [ ] Inspect the floor mats for rips, stains, etc.
- [ ] Inspect the metal accelerator and brake pedal arms; there have been
[reports](https://www.reddit.com/r/TeslaModelY/comments/gyhim1/is_this_normal_my_brake_pedal_arm_has_a_welded/) of
different finish on pedals (matte on accelerator, glossy on brake) and a conspicuous weld in the middle of the brake pedal
- [ ] Turn on climate control, force the heat pump to kick in by taking the temperature to either end of the scale and listen for loud noises
- [ ] Confirm (car battery) charging works

## Frunk

- [ ] Open and close the frunk
- [ ] Verify the clips holding the trim area around the frunk
- [ ] Confirm the tow hook isn't missing

## Trunk

- [ ] Open & close the lift gate; sometimes the gasket gets caught in the molding, causing a click 
- [ ] Confirm the lift gate opens and closes without "shuddering" and that the button on the hatch works to close it
- [ ] Inspect the cargo covers and verify they're properly attached
- [ ] Confirm that seat & trunk buttons fold the back seats
- [ ] Confirm folding rear seats do not catch on the rear trunk floor carpeting 
- [ ] Inspect the back seat covers and verify they're properly attached
- [ ] Confirm the charging cable and the [J1772 adapter](https://shop.tesla.com/product/sae-j1772-charging-adapter) aren't missing

## Final thoughts about your delivery inspection

Please don't be "that guy" that blocks Tesla deliveries and staff for hours while going over your new car with a microscope!
You can report all of the above after you get home, at your leisure: you have a day/100 miles. It’s not like you won’t
accept the car because of some minor issue that can be fixed by a mobile service tech later (but won’t be fixed at
pickup).  Critical things to check on site are VIN, color, wheels, etc. and critical safety, like being able to
lock/unlock the car and put it in park.  Visit and check the local super charger while you are there, too.

## What next?

Should anything escape factory QC, service center QC, and the above cheklist here are some options to be aware of:

- If the quality of the car is inadequate you can **refuse delivery**. There have been several refused delivery reports
([1](https://www.reddit.com/r/TeslaModelY/comments/hgewe8/rejected_delivery_today_vin_012xxx/), 
[2](https://www.reddit.com/r/TeslaModelY/comments/hgvjee/follow_up_image_from_my_other_post_here_was_the/),
[3](https://www.reddit.com/r/TeslaModelY/comments/hgew40/model_y_rejected_delivery_today/),
[4](https://www.reddit.com/r/TeslaModelY/comments/hfuum2/deferred_my_delivery/),
[5](https://www.reddit.com/r/TeslaModelY/comments/hfb1vg/cancelled_model_y_delivery/),
[6](https://www.reddit.com/r/TeslaModelY/comments/hete2x/update_rejected_delivery/)), check out the threads
 for details. Following that you should be assigned a new VIN.
 
- After leaving the lot you have 72 hours/100 miles to **report delivery issues to be fixed free of charge**. The 72 hours
refers to items subject to "wear and tear," such as paint defects, scratches, etc. Any item that would normally be covered
under warranty is still covered under warranty, but things like blemishes, scratches, dings, scuffs, aren't covered by any
other car company. However check [this thread](https://www.reddit.com/r/TeslaModelY/comments/hh8mgv/rattling_in_back_seats_reported_within_7_days/)
about a problem reported within the first 7 days of ownership and being asked to accept a cost estimate.

> Note: the information about refusing delivery and reporting delivery issues has been
> contributed by several people. I couldn't find the authoritative source; pointers appreciated. 

- As a last resort you have [7 calendar days/1000 miles](https://www.tesla.com/support/tesla-return-policy) to **return the car**
(here's a [first-hand account](https://www.reddit.com/r/TeslaModelY/comments/heb5cu/i_changed_my_mind_im_returning_my_model_y/)).
Note that doing so restricts your next Tesla order: "If you decide to order another vehicle, you may not order the same trim for
a period of 12 months but may order another vehicle in a different trim at any time."

Pull requests for changes/additions welcome.
